version: "3.9"

services:
  app:
    build: .
    container_name: weather_app
    restart: on-failure
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - weather_net

  db:
    image: postgres:16
    container_name: weather_db
    restart: always
    environment:
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: WeatherApp
    ports:
      - "4444:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - weather_net

volumes:
  pgdata:

networks:
  weather_net:
    driver: bridge
